server:
  port: 8081

mybatis:
  type-aliases-package: com.wang.pojo
#  mybatis配置路径
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper配置路径
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: 123456

